version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    working_dir: /app/api
    volumes:
      - ./:/app
      - /app/node_modules
    command: ["bun", "run", "app.js"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
